framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - validation
                    - doctrine_transaction
            messenger.bus.queries:
                middleware:
                    - validation
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            App\CoffeeMachine\Application\Event\MachineStartedEvent: async
            App\CoffeeMachine\Application\Event\MachineStoppedEvent: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
